name: create typescript model workflow

on:
  push:
    branches:
      - feature/jsonschema-to-typescript

jobs:
  jsonschema-to-typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Generate
        run: npm start
      - name: Add to git
        run: git add .
      - name: Commit
        run: git commit -m "Update typescript model"
      - name: Push
        run: git push origin feature/jsonschema-to-typescript
     